const TeamDomain = ['CORE TEAM', 'SENIOR ADVISORS', 'DEVELOPERS', 'DESIGNERS', 'CONTENT AND CREATIVE', 'MARKETING TEAM', 'EXTERNAL AFFAIRS', 'PUBLIC RELATION', 'EVENT CO-ORDINATORS'];
const TeamMemberName = [
  ['Akshat Jain', 'Pranav Mittal', 'Bisesh Agarwal', 'Atharva Bhatt', 'Mayank Singh', 'Sarang Manerikar', 'Shivansh Dubey', 'Suhani Agrawal', 'Raghav Agrawal', 'Suryansh Singh', 'Akshit Singla', 'Ayush Bemera', 'Ankur Agrawal', 'Raina Jain', 'Nishant Gounder', 'Avinash Singh', 'Ayushi Gupta', 'Ankit'],
  ['Yash Jain', 'Vikash Prajapati', 'Vikhyath Venkatraman', 'Siddharth Anand Srivastav', 'Eshaan Gupta', 'Smriti Sharma', 'Prajakta Priyadarshini', 'Nisitha Vallamdasu', 'Prince Kumar Gond', 'Aditya Agarwal', 'Swastik Thapa'],
  ['Ankur Agrawal', 'Raina Jain', 'Akash Kumar', 'Avnesh Kumar', 'Kumar Sonu', 'Dhruv Chaudhary', 'Anant Jain', 'Md Athar', 'Shubham Jaiswal', 'Ashish Kumar', 'Nikhil Agarwal', 'Archit Pattanaik', 'Harshit Swarnkar', 'Nikhil Aggarwal', 'Samarth Tankasali', 'Samar Singh Randhawa', 'Mamalesh Rajkumar Hake'],
  ['Devi Tanuja Vasamsetty', 'Korivi Vedharshini', 'Riya Saini', 'Kalpit Adhao', 'Shivam Gupta', 'Aditya Mishra', 'Jasnoor Sandhu', 'Nilesh Sangle', 'Md Athar', 'Niharika Singh'],
  ['Shubhi Singh', 'Archit Soni', 'Pratishtha Dhiraj', 'P V Krishna Priya', 'Tarun Siddharth', 'Sakshi Tomar', 'Anusha Mahajan', 'Ritesh Lakra', 'Dharmesh Mahajan', 'Shrirang Gupta', 'Avani Jangid', 'Saket Kumar Singh'],
  [
    'Nishant Gounder',
    'Pushpam Berlia',
    'Harsh Singh',
    'Deependra Singh',
    'Abhishek Kumar',
    'Majjiga Deepak Sai',
    'Sachin Kumar',
    'Umang Garg',
    'Tarun Kumar Painkra',
    'Divyansh Jain',
    'Abhishek Kumar',
    'Rishav Kumar',
    'Konam Harshitha',
    'Suraj Gaur',
    'Jarpula Ajay Nayak',
    'Ipil Besra',
    'Vedansh Arya',
    'Dhruv Sharma',
    'Mitra Pidaparti',
    'Ayush Harshit',
    'Gargi Nigam',
    'Simarpreet Singh',
    'Mauli Gupta',
    'Ashutosh Awasthi'
  ],
  ['Ayushi Gupta', 'Ankit', 'Shreyansh Jain', 'Shubham Kumar', 'Mohit Singh', 'Riya Chauhan', 'Amit Kumar', 'Harsh Kumar', 'Anshu Soni', 'Shivam Raj', 'Harsh Saini', 'Shivom', 'Vaatsalya Sinha', 'Rajat Shukla'],
  ['Avinash Singh', 'Bhavna Chavan', 'Priyanshu', 'Divyanshu', 'Ravi Kumar Meena', 'Jaya Kedia', 'Anupam Shukla', 'Vaibhav Gupta', 'Harshit Anand', 'Anshu Kumar', 'Utkarsh Kumar', 'Aditya chandel', 'Aditya kumar', 'Mendapara Khelankumar', 'Aryan Sinha', 'Rakshit Sawhney', 'Ayush Singh'],
  [
    'Sanskar Totla',
    'Shubham Garg',
    'Aryan',
    'Vivek Agarwal',
    'Dhruv Agarwal',
    'Srini Rohan',
    'Vaibhav Tripathi',
    'Vishal U Gosain',
    'Sandeepan Ghosh',
    'Ayush Agarwal',
    'P V Krishna Priya',
    'Ajinkya Rajendra Mohale',
    'Sachin Shaw',
    'Naveen Yadav',
    'Udit Agarwal',
    'Saumya Chaudhary',
    'Vikrant',
    'Gagan Mundada',
    'Bhargavi Kiran',
    'Saurabh Maurya',
    'Chaithanya Krishna',
    'Sravya Damarla',
    'Kanchan',
    'Gopal Krishna Yadav',
    'Aritra Dutta',
    'Dasari Dhathri Chandra',
    'Akshat Gupta',
    'Anvesh Gupta',
    'Mohit Kumar Agrawal',
    'Purav Haran',
    'Prabhat Kumar',
    'Rohit Kumar Gautam',
    'Jayesh Upadhyay',
    'Bollepalli Sandeep Raju',
    'Mausam Singh',
    'Sanidhya Verma',
    'Harsha Sree Sanapala',
    'Shreyansh Jain',
    'Pawan Kumar',
    'Nishant Goounder',
    'Pushpam Berlia',
    'Archit Soni',
    'Mehul Kumar Sahoo',
    'Ankur Shandilya',
    'Allu Sai Neha',
    'Vidhan Palresha',
    'Vinit Sharma',
    'Piyush Kumar Lodwal',
    'Devpal Dan',
    'YOGYATA SINGH',
    'Palti Sumasri',
    'Bhupendra Kumar Dhruw',
    'Tushar Karale',
    'Kuldeep singh',
    'Aman Agrawal',
    'Om Verma'
  ]
];
const MemberImage = [
  [
    '/assets/TeamsSectionImages/Akshat jain.jpg',
    '/assets/TeamsSectionImages/Pranav_Mittal.jpg',
    '/assets/TeamsSectionImages/Bisesh Agarwal.jpg',
    '/assets/TeamsSectionImages/Atharva_Bhatt.jpg',
    '/assets/TeamsSectionImages/Mayank Singh.JPG',
    '/assets/TeamsSectionImages/Sarang Manerikar.jpg',
    '/assets/TeamsSectionImages/Shivansh_Dubey.jpg',
    '/assets/TeamsSectionImages/Suhani Agrawal.jpeg',
    '/assets/TeamsSectionImages/Raghav Agrawal.jpg',
    '/assets/TeamsSectionImages/Suryansh Singh.png',
    '/assets/TeamsSectionImages/Akshit Singla.jpg',
    '/assets/TeamsSectionImages/Bemera Ayush.PNG',
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Raina Jain.jpg',
    '/assets/TeamsSectionImages/Nishanth Gounder.jpg',
    '/assets/TeamsSectionImages/Avinash Singh.jpeg',
    '/assets/TeamsSectionImages/Ayushi Gupta.jpg',
    '/assets/TeamsSectionImages/Ankit.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Yash_Jain.jpg',
    '/assets/TeamsSectionImages/Vikash_Prajapati.jpg',
    '/assets/TeamsSectionImages/Vikhyath Venkatraman.jpg',
    '/assets/TeamsSectionImages/Siddharth Anand Srivastav.jpeg',
    '/assets/TeamsSectionImages/Eshaan Gupta.jpeg',
    '/assets/TeamsSectionImages/Smriti_Sharma.jpg',
    '/assets/TeamsSectionImages/Prajakta Priyadarshini.jpg',
    '/assets/TeamsSectionImages/Nisitha Vallamdasu.jpg',
    '/assets/TeamsSectionImages/Prince Kumar Gond.jpg',
    '/assets/TeamsSectionImages/Aditya Agarwal.jpg',
    '/assets/TeamsSectionImages/Swastik Thapa.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Raina Jain.jpg',
    '/assets/TeamsSectionImages/Akash_Kumar.jpg',
    '/assets/TeamsSectionImages/Avnesh kumar.jpg',
    '/assets/TeamsSectionImages/Kumar Sonu.jpeg',
    '/assets/TeamsSectionImages/Dhruv Chaudhary.jpg',
    '/assets/TeamsSectionImages/Anant Jain.jpg',
    '/assets/TeamsSectionImages/Md_Athar.jpg',
    '/assets/TeamsSectionImages/Shubham Jaiswal.jpg',
    '/assets/TeamsSectionImages/Ashish Kumar.jpeg',
    '/assets/TeamsSectionImages/Nikhil Agarwal.jpg',
    '/assets/TeamsSectionImages/Archit Pattanaik.jpeg',
    '/assets/TeamsSectionImages/Harshit Swarnkar.jpeg',
    '/assets/TeamsSectionImages/Nikhil Aggarwal.jpeg',
    '/assets/TeamsSectionImages/Samarth S T.jpg',
    '/assets/TeamsSectionImages/Samar Singh Randhawa.jpg',
    '/assets/TeamsSectionImages/blank-photo.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Devi_Tanuja_Vasamsetty.jpg',
    '/assets/TeamsSectionImages/Korivi Vedharshini.jpg',
    '/assets/TeamsSectionImages/Riya Saini.jpg',
    '/assets/TeamsSectionImages/Kalpit Adhao.jpg',
    '/assets/TeamsSectionImages/Shivam Gupta.jpg',
    '/assets/TeamsSectionImages/Aditya Mishra.jpeg',
    '/assets/TeamsSectionImages/Jasnoor Sandhu.jpeg',
    '/assets/TeamsSectionImages/Nilesh Sangle.jpg',
    '/assets/TeamsSectionImages/Md_Athar.jpg',
    '/assets/TeamsSectionImages/Niharika Singh.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Shubhi Singh.jpg',
    '/assets/TeamsSectionImages/Archit Soni.jpg',
    '/assets/TeamsSectionImages/Pratistha Dhiraj.jpg',
    '/assets/TeamsSectionImages/P V Krishna Priya.jpg',
    '/assets/TeamsSectionImages/Tarun Siddharth.jpeg',
    '/assets/TeamsSectionImages/Sakshi Tomar.jpg',
    '/assets/TeamsSectionImages/Anusha Mahajan.jpg',
    '/assets/TeamsSectionImages/Ritesh Lakra.jpeg',
    '/assets/TeamsSectionImages/Dharmesh Mahajan.jpg',
    '/assets/TeamsSectionImages/Shrirang Gupta.jpeg',
    '/assets/TeamsSectionImages/Avani Jangid.jpeg',
    '/assets/TeamsSectionImages/Saket Kumar Singh.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Nishanth Gounder.jpg',
    '/assets/TeamsSectionImages/Pushpam Berlia.jpg',
    '/assets/TeamsSectionImages/Harsh Singh.jpg',
    '/assets/TeamsSectionImages/Deependra Singh.jpg',
    '/assets/TeamsSectionImages/Abhishek Kumar.jpg',
    '/assets/TeamsSectionImages/Majjiga Deepak Sai.jpg',
    '/assets/TeamsSectionImages/Sachin Kumar.jpg',
    '/assets/TeamsSectionImages/Umang Garg.jpeg',
    '/assets/TeamsSectionImages/Tarun Kumar Painkra.jpg',
    '/assets/TeamsSectionImages/Divyansh Jain.jpeg',
    '/assets/TeamsSectionImages/Abhishek Kumar(T).jpg',
    '/assets/TeamsSectionImages/Rishav Kumar.jpg',
    '/assets/TeamsSectionImages/Konam Harshitha.jpg',
    '/assets/TeamsSectionImages/Suraj Gaur.jpg',
    '/assets/TeamsSectionImages/Jarpula Ajay Nayak.jpg',
    '/assets/TeamsSectionImages/Ipil Besra.jpg',
    '/assets/TeamsSectionImages/blank-photo.jpg',
    '/assets/TeamsSectionImages/Dhruv Sharma.jpg',
    '/assets/TeamsSectionImages/Mitra Pidaparti.jpeg',
    '/assets/TeamsSectionImages/Ayush Harshit.jpg',
    '/assets/TeamsSectionImages/Gargi Nigam.jpeg',
    '/assets/TeamsSectionImages/Simarpreet Singh.jpeg',
    '/assets/TeamsSectionImages/Mauli Gupta.jpg',
    '/assets/TeamsSectionImages/Ashutosh Awasthi.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Ayushi Gupta.jpg',
    '/assets/TeamsSectionImages/Ankit.jpg',
    '/assets/TeamsSectionImages/Shreyansh Jain.jpg',
    '/assets/TeamsSectionImages/Shubham Kumar.jpeg',
    '/assets/TeamsSectionImages/Mohit Singh.jpg',
    '/assets/TeamsSectionImages/Riya Chauhan.jpg',
    '/assets/TeamsSectionImages/Amit Kumar.jpg',
    '/assets/TeamsSectionImages/Harsh Kumar.jpg',
    '/assets/TeamsSectionImages/Anshu Soni.jpg',
    '/assets/TeamsSectionImages/Shivam Raj.jpg',
    '/assets/TeamsSectionImages/Harsh Saini.jpg',
    '/assets/TeamsSectionImages/Shivom.jpg',
    '/assets/TeamsSectionImages/Vaatsalya Sinha.jpg',
    '/assets/TeamsSectionImages/Rajat Shukla.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Avinash Singh.jpeg',
    '/assets/TeamsSectionImages/Bhavna Chavan.jpg',
    '/assets/TeamsSectionImages/Priyanshu.jpg',
    '/assets/TeamsSectionImages/Divyanshu Devashish.jpg',
    '/assets/TeamsSectionImages/Ravi Kumar Meena.jpeg',
    '/assets/TeamsSectionImages/Jaya Kedia.jpg',
    '/assets/TeamsSectionImages/Anupam Shukla.jpg',
    '/assets/TeamsSectionImages/Vaibhav Gupta.jpg',
    '/assets/TeamsSectionImages/Harshit Anand.jpg',
    '/assets/TeamsSectionImages/Anshu Kumar.jpg',
    '/assets/TeamsSectionImages/Utkarsh Kumar.jpg',
    '/assets/TeamsSectionImages/Aditya Chandel.jpg',
    '/assets/TeamsSectionImages/Aditya Kumar.jpg',
    '/assets/TeamsSectionImages/Khelan Kumar.jpg',
    '/assets/TeamsSectionImages/Aryan Sinha.jpg',
    '/assets/TeamsSectionImages/Rakshit Sawhney.jpg',
    '/assets/TeamsSectionImages/Ayush Singh.jpg'
  ],
  [
    '/assets/TeamsSectionImages/Sanskar Totla.jpg',
    '/assets/TeamsSectionImages/Shubham Garg.jpg',
    '/assets/TeamsSectionImages/Mr. Aryan.jpg',
    '/assets/TeamsSectionImages/Vivek Agarwal.jpg',
    '/assets/TeamsSectionImages/Dhruv Agarwal.jpg',
    '/assets/TeamsSectionImages/Srini Rohan.jpg',
    '/assets/TeamsSectionImages/Vaibhav Tripathi.jpg',
    '/assets/TeamsSectionImages/Vishal Gosain.jpeg',
    '/assets/TeamsSectionImages/Sandeepan Ghosh.jpg',
    '/assets/TeamsSectionImages/Ayush Agarwal.jpeg',
    '/assets/TeamsSectionImages/P V Krishna Priya.jpg',
    '/assets/TeamsSectionImages/Mohale Ajinkya Rajendra.jpg',
    '/assets/TeamsSectionImages/Sachin Shaw.jpg',
    '/assets/TeamsSectionImages/Naveen Yadav.jpg',
    '/assets/TeamsSectionImages/Udit Agarwal.jpg',
    '/assets/TeamsSectionImages/Saumya Chaudhary.jpg',
    '/assets/TeamsSectionImages/Vikrant.jpg',
    '/assets/TeamsSectionImages/Gagan Mundada.jpeg',
    '/assets/TeamsSectionImages/Bhargavi Kiran.jpg',
    '/assets/TeamsSectionImages/Saurabh Maurya.png',
    '/assets/TeamsSectionImages/Chaithanya Krishna.jpg',
    '/assets/TeamsSectionImages/Sravya Damarla.jpg',
    '/assets/TeamsSectionImages/Kanchan.JPG',
    '/assets/TeamsSectionImages/Gopal Krishna Yadav.jpg',
    '/assets/TeamsSectionImages/Aritra Datta.jpeg',
    '/assets/TeamsSectionImages/Dasari Dhathri Chandra.jpg',
    '/assets/TeamsSectionImages/Akshat Gupta.jpeg',
    '/assets/TeamsSectionImages/Anvesh Gupta.jpg',
    '/assets/TeamsSectionImages/Mohit Agrawal.jpg',
    '/assets/TeamsSectionImages/Purav Haran.jpg',
    '/assets/TeamsSectionImages/Prabhat Kumar.jpg',
    '/assets/TeamsSectionImages/Rohit Kumar Gautam.jpg',
    '/assets/TeamsSectionImages/Jayesh Upadhyay.jpg',
    '/assets/TeamsSectionImages/Bollepalli Sandeep Raju.jpeg',
    '/assets/TeamsSectionImages/Mausam Singh.jpg',
    '/assets/TeamsSectionImages/Sanidhya Verma.jpg',
    '/assets/TeamsSectionImages/Sanapala Harsha Sree.jpg',
    '/assets/TeamsSectionImages/Shreyansh Jain.jpg',
    '/assets/TeamsSectionImages/Pawan Kumar.jpeg',
    '/assets/TeamsSectionImages/Nishanth Gounder.jpg',
    '/assets/TeamsSectionImages/Pushpam Berlia.jpg',
    '/assets/TeamsSectionImages/Archit Soni.jpg',
    '/assets/TeamsSectionImages/Mehul Kumar Sahoo.jpg',
    '/assets/TeamsSectionImages/blank-photo.jpg',
    '/assets/TeamsSectionImages/Allu Sai Neha.jpg',
    '/assets/TeamsSectionImages/Vidhan Palresha.jpg',
    '/assets/TeamsSectionImages/Vinit Sharma.jpg',
    '/assets/TeamsSectionImages/Piyush Kumar Lodwal.jpg',
    '/assets/TeamsSectionImages/Devpal Dan.jpeg',
    '/assets/TeamsSectionImages/Yogyata Singh.jpg',
    '/assets/TeamsSectionImages/Palti Sumasri.jpg',
    '/assets/TeamsSectionImages/Bhupendra Kumar Dhruw.jpg',
    '/assets/TeamsSectionImages/KArale Tushar Bharat.jpg',
    '/assets/TeamsSectionImages/Kuldeep Singh.jpg',
    '/assets/TeamsSectionImages/Aman Agrawal.jpg',
    '/assets/TeamsSectionImages/blank-photo.jpg'
  ]
];
const Designation = [
  ['Convener', 'General Secretary', 'Co-Convener', 'Joint Gen Secy', 'Joint Gen Secy', 'Joint Gen Secy', 'Tech Secy', 'Tech Secy', 'Cult Secy', 'Cult Secy', 'Sports Secy', 'Sports Secy', 'Web Head', 'Web Head', 'Marketing Head', 'PR Head', 'External Affairs Head', 'External Affairs Head'],
  ['Senior web advisor', 'Senior Advisor External Affairs', 'Senior Advisor', 'Senior Advisor (Design)', 'Senior Tech Advisor', 'Senior Tech Advisor', 'Senior Advisor', 'Senior Advisor (Content and Creative)', 'Senior Adivisor (Public Relations)', 'Senior Advisor (Udgam)', 'Sports Secretary'],
  ['Web Head', 'Web Head', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator', 'Web Coordinator'],
  ['Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Cordinator', 'Co-Cordinator', 'Co-Cordinator', 'Co-Cordinator', 'Co-Cordinator'],
  ['Content Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator'],
  [
    'Marketing Head',
    'Coordinator',
    'Coordinator',
    'Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator',
    'Co-Coordinator'
  ],
  ['Head', 'Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator'],
  ['Head', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator'],
  [
    'Devbits Coordinator',
    'Devbits Coordinator',
    'Devbits Coordinator',
    'Mosaic Coordinator',
    'Mosaic Coordinator',
    'Mosaic Coordinator',
    'Cassandra Coordinator',
    'Cassandra Coordinator',
    'Digisim Coordinator',
    'Digisim Coordinator',
    'X-IoTA Coordinator',
    'X-IoTA Coordinator',
    'Commnet Coordinator',
    'I-Chip Coordinator',
    'I-Chip Coordinator',
    'Funckit Coordinator',
    'Udgam Coordinator',
    'Udgam Coordinator',
    'Udgam Coordinator',
    'Udgam Coordinator',
    'Udgam Coordinator',
    'Udgam Coordinator (Music)',
    'Udgam Coordinator (Literary)',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Udgam Co-Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator',
    'Mashal Coordinator (Badminton)',
    'Mashal Coordinator (Badminton)',
    'Mashal Coordinator (Valorant)',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator',
    'Mashal Co-Coordinator'
  ]
];
const TeamMemberDetails = [
  ['Fourth Yearite', 'Fourth Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite'],
  ['Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite', 'Fourth Yearite'],
  ['Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  [
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite'
  ],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  [
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Third Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite',
    'Second Yearite'
  ]
];
const ContactMail = [
  [
    'akshat.rajkumarjain.ece19@itbhu.ac.in',
    'pranav.mittal.ece19@itbhu.ac.in',
    'bisesh.agarwal.ece20@itbhu.ac.in',
    'atharva.bhatt.ece20@itbhu.ac.in',
    'mayank.singh.ece20@itbhu.ac.in',
    'sarang.manerikar.ece20@itbhu.ac.in',
    'shivansh.dubey.ece20@itbhu.ac.in',
    'suhani.agrawal.ece20@itbhu.ac.in',
    'raghav.agrawal.cd.ece20@itbhu.ac.in',
    'suryansh.singh.cd.ece20@itbhu.ac.in',
    'akshit.singla.ece20@itbhu.ac.in',
    'bemera.ayush.ece20@itbhu.ac.in',
    'ankur.agrawal.ece20@itbhu.ac.in',
    'raina.jain.ece20@itbhu.ac.in',
    'nishanth.gounder.ece20@itbhu.ac.in',
    'avinash.singh.ece20@itbhu.ac.in',
    'ayushi.gupta.ece20@itbhu.ac.in',
    'ankit.student.ece20@itbhu.ac.in'
  ],
  [
    'yash.jain.ece19@itbhu.ac.in',
    'vikash.prajapati.ece19@itbhu.ac.in',
    'vikhyath.pvenkatraman.ece19@itbhu.ac.in',
    'siddharth.asrivastav.ece19@itbhu.ac.in',
    'eshaangupta1708@gmail.com',
    'smriti.sharma.ece19@itbhu.ac.in',
    'prajakta.priyadarsini.ece19@itbhu.ac.in',
    'nisitha.vallamdasu.ece19@itbhu.ac.in',
    'princekumar.gond.ece19@itbhu.ac.in',
    'aditya.agarwal.ece19@itbhu.ac.in',
    'swastikthapa125@gmail.com'
  ],
  [
    'ankur.agrawal.ece20@itbhu.ac.in',
    'raina.jain.ece20@itbhu.ac.in',
    'akash.kumar.ece21@itbhu.ac.in',
    'avnesh.kumar.ece21@itbhu.ac.in',
    'kumar.sonu.ece21@itbhu.ac.in',
    'dhruv.chaudhary.ece21@itbhu.ac.in',
    'anant.jain.ece21@itbhu.ac.in',
    'md.athar.ece21@itbhu.ac.in',
    'shubham.jaiswal.ece21@itbhu.ac.in',
    'ashish.kumar.ece21@itbhu.ac.in',
    'nikhil.agarwal.ece21@itbhu.ac.in',
    'archit.pattanaik.ece21@itbhu.ac.in',
    'harshit.swarnkar.ece21@itbhu.ac.in',
    'nikhil.aggarwa.ece21@itbhu.ac.in',
    'samarth.stankasali.ece21@itbhu.ac.in',
    'samarsingh.randhawa.ece21@itbhu.ac.in',
    ''
  ],
  ['dtanuja.vasamsetty.ece20@itbhu.ac.in', 'korivi.vedharshini.ece20@itbhu.ac.in', 'riya.saini.ece20@itbhu.ac.in', 'kalpit.adhao.ece20@itbhu.ac.in', 'shivam.gupta.ece21@itbhu.ac.in', 'aditya.mishra.ece21@itbhu.ac.in', 'jas9noor@gmail.com', 'snilesh.ganesh.ece21@itbhu.ac.in', 'md.athar.ece21@itbhu.ac.in', 'niharika.singh.ece21@itbhu.ac.in'],
  [
    'shubhi.singh.ece20@itbhu.ac.in',
    'archit.soni.ece20@itbhu.ac.in',
    'pratishtha.dhiraj.ece20@itbhu.ac.in',
    'potnuru.vkrishnapriya.ece20@itbhu.ac.in',
    'starun.siddharth.ece21@itbhu.ac.in',
    'sakshi.tomar.ece21@itbhu.ac.in',
    'anusha.mahajan.ece21@itbhu.ac.in',
    'ritesh.lakra.ece21@itbhu.ac.in',
    'dharmesh.mahajan.ece21@itbhu.ac.in',
    'sbrajesh.gupta.ece21@itbhu.ac.in',
    'avani.jangid.cd.ece21@itbhu.ac.in',
    'saket.kumarsingh.ece21@itbhu.ac.in'
  ],
  [
    'nishanth.gounder.ece20@itbhu.ac.in',
    'pushpam.berlia.ece20@itbhu.ac.in',
    'harsh.singh.ece20@itbhu.ac.in',
    'deependra.singh.ece20@itbhu.ac.in',
    'abhishek.ukumar.ece21@itbhu.ac.in',
    'majjiga.deepaksai.ece21@itbhu.ac.in',
    'sachin.kumar.ece21@itbhu.ac.in',
    'umang.garg.ece21@itbhu.ac.in',
    'tarunkumar.painkra.ece21@itbhu.ac.in',
    'divyansh.jain.ece21@itbhu.ac.in',
    'abhishek.kumar.ece21@itbhu.ac.in',
    'rishav.kumar.cd.ece21@itbhu.ac.in',
    'konam.harshitha.ece21@itbhu.ac.in',
    'suraj.gaur.ece21@itbhu.ac.in',
    'jarpulaajay.nayak.ece21@itbhu.ac.in',
    'ipil.besra.ece21@itbhu.ac.in',
    'vedansh.arya.ece21@itbhu.ac.in',
    'dhruv.sharma.ece21@itbhu.ac.in',
    'mitra.pidaparti.ece21@itbhu.ac.in',
    'ayush.harshit.ece21@itbhu.ac.in',
    'gargi.nigam.ece21@itbhu.ac.in',
    'simarpreet.singh.ece21@itbhu.ac.in',
    'mauli.gupta.cd.ece21@itbhu.ac.in',
    'ashutosh.awasthi.ece21@itbhu.ac.in'
  ],
  [
    'ayushi.gupta.ece20@itbhu.ac.in',
    'ankit.student.ece20@itbhu.ac.in',
    'shreyansh.jain.ece20@itbhu.ac.in',
    'shubhamk.ece20@itbhu.ac.in',
    'mohit.singh.cd.ece20@itbhu.ac.in',
    'riya.chauhan.ece21@itbhu.ac.in',
    'amit.kumar.ece21@itbhu.ac.in',
    'harsh.kumar.ece21@itbhu.ac.in',
    'anshu.soni.ece21@iitbhu.ac.in',
    'shivam.raj.ece21@itbhu.ac.in',
    'harsh.saini.ece21@itbhu.ac.in',
    'shivom.student.ece21@itbhu.ac.in',
    'vaatsalya.sinha.ece21@itbhu.ac.in',
    'rajat.shukla.ece21@itbhu.ac.in'
  ],
  [
    'avinash.singh.ece20@itbhu.ac.in',
    'bhavna.student.ece20@itbhu.ac.in',
    'priyanshu.student.ece21@itbhu.ac.in',
    'divyanshu.student.ece21@itbhu.ac.in',
    'ravikumar.meena.ece21@itbhu.ac.in',
    'jaya.kedia.cd.ece21@itbhu.ac.in',
    'anupam.shukla.ece21@itbhu.ac.in',
    'vaibhav.gupta.ece21@itbhu.ac.in',
    'harshit.anand.ece21@itbhu.ac.in',
    'anshu.kumar.ece21@itbhu.ac.in',
    'utkarsh.kumar.ece21@itbhu.ac.in',
    'aditya.chandel.ece21@itbhu.ac.in',
    'aditya.kumar.ece21@itbhu.ac.in',
    'mkhelank.hasmukhbhai.ece21@itbhu.ac.in',
    'aryan.sinha.ece21@itbhu.ac.in',
    'rakshit.sawhney.ece21@itbhu.ac.in',
    'ayush.singh.ece21@it.bhu.ac.in'
  ],
  [
    'sanskar.santoshtotla.ece20@itbhu.ac.in',
    'shubham.garg.ece20@itbhu.ac.in',
    'aryan.student.cd.ece20@itbhu.ac.in',
    'vivek.agarwal.ece20@itbhu.ac.in',
    'dhruv.agarwal.ece20@itbhu.ac.in',
    'gujullal.srinirohan.ece20@itbhu.ac.in',
    'vaibhav.tripathi.ece20@itbhu.ac.in',
    'vishal.ugosain.ece20@itbhu.ac.in',
    'sandeepan.ghosh.ece20@itbhu.ac.in',
    'ayush.agarwal.ece20@itbhu.ac.in',
    'potnuru.vkrishnapriya.ece20@itbhu.ac.in',
    'majinkya.rajendra.ece20@iitbhu.ac.in',
    'sachin.shaw.ece20@itbhu.ac.in',
    'naveen.kumaryadav.ece20@iitbhu.ac.in',
    'udit.agarwal.ece20@itbhu.ac.in',
    'saumya.chaudhary.ece20@itbhu.ac.in',
    'vikrant.student.ece20@itbhu.ac.in',
    'gagan.mundada.cd.ece20@itbhu.ac.in',
    'bhargavi.kiran.ece20@itbhu.ac.in',
    'saurabh.maurya.ece20@itbhu.ac.in',
    'munagala.ckrishna.ece20@itbhu.ac.in',
    'damarla.sravya.ece20@itbhu.ac.in',
    'kanchan.student.ece20@itbhu.ac.in',
    'gopalkrishna.yadav.cd.ece21@itbhu.ac.in',
    'aritra.datta.cd.ece21@itbhu.ac.in',
    'ddhathri.chandra.ece21@itbhu.ac.in',
    'akshat.gupta.ece21@itbhu.ac.in',
    'anvesh.gupta.ece21@itbhu.ac.in',
    'mohitkumar.agrawal.ece21@itbhu.ac.in',
    'purav.haran.ece21@itbhu.ac.in',
    'prabhat.kumar.cd.ece20@iitbhu.ac.in',
    'rohikumar.gautam.ece20@itbhu.ac.in',
    'jayesh.upadhyay.ece20@itbhu.ac.in',
    'bollepalli.sandeepr.ece20@itbhu.ac.in',
    'mausam.singh.ece20@itbhu.ac.in',
    'sanidhya.verma.ece20@itbhu.ac.in',
    'sanapala.harshasree.ece20@itbhu.ac.in',
    'shreyansh.jain.ece20@itbhu.ac.in',
    'pawan.kumar.ece20@itbhu.ac.in',
    'nishanth.gounder.ece20@itbhu.ac.in',
    'pushpam.berlia.ece20@iitbhu.ac.in',
    'archit.soni.ece20@itbhu.ac.in',
    'mehul.kumarsahoo.ece21@itbhu.ac.in',
    'ankur.shandilya.ece21@itbhu.ac.in',
    'allusai.neha.ece21@itbhu.ac.in',
    'vidhan.palresha.ece21@itbhu.ac.in',
    'vinit.sharma.ece21@itbhu.ac.in',
    'piyush.krlodwal.ece21@itbhu.ac.in',
    'devpal.dan.ece21@itbhu.ac.in',
    'yogyata.singh.ece21@itbhu.ac.in',
    'palti.sumasri.ece21@itbhu.ac.in',
    'bhupendra.kdhruw.ece21@itbhu.ac.in',
    'karaletushar.bharat.ece21@itbhu.ac.in',
    'kuldeep.singh.ece21@itbhu.ac.in',
    'aman.agrawal.ece21@itbhu.ac.in',
    'om.verma.ece21@itbhu.ac.in'
  ]
];
const ContactInstagram = [
  [
    '',
    'https://www.instagram.com/pranav_2x1/',
    'https://instagram.com/dynamic_agarwal?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/bhattatharva?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/mayank_s_ingh_',
    'https://www.instagram.com/',
    'https://www.instagram.com/shivansh_d_/',
    'https://www.instagram.com/suhanii_97/?igshid=ZDdkNTZiNTM%3D',
    'https://www.instagram.com/ag_raghav26/',
    'https://instagram.com/_surya__ss?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/akshit._.singla/',
    '',
    'https://instagram.com/ankuragrawal9455?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/raina_jainn/',
    'https://www.instagram.com/nishu_07.02/',
    'http://www.instagram.com/avinash.singh___',
    'https://instagram.com/ayushigupta400?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/ank.it7410?igshid=ZDdkNTZiNTM='
  ],
  [
    'https://instagram.com/yashjain484?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/vikash_0307?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/obstinately_awesome/',
    'https://instagram.com/_siddharth__101?igshid=MWI4MTIyMDE=',
    'https://instagram.com/this.is.eshaan?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/_.simi_06',
    'https://instagram.com/_._minniee.__?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/nisitha_565?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/_prince_0911?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/justchill_adi?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/swstk_125?igshid=ZDdkNTZiNTM='
  ],
  [
    'https://instagram.com/ankuragrawal9455?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/raina_jainn/',
    'https://instagram.com/akash_kourav03?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/avnesh141?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/k_sonu6091/',
    'https://www.instagram.com/dhruv_chaudhary_1380/',
    'https://www.instagram.com/anant_jain_01/',
    'https://www.instagram.com/mdathar44__/',
    'https://www.instagram.com/shubham_jai.swal/',
    'https://www.instagram.com/ashish_7515/?next=%2F',
    'https://www.instagram.com/nik__agarwal12/',
    'https://www.instagram.com/architpattanaik2/',
    'https://www.instagram.com/rew__06/',
    'https://www.instagram.com/nikhilaggarwal.__',
    'https://instagram.com/_.cat.junkie._?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/randhawasamarsingh/',
    'https://www.instagram.com/mamaleshhake/'
  ],
  [
    'https://instagram.com/tanuja_winniee?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/vedharshinikorivi?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/r.i.y.a_s.a.i.n.i?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/kalpit_adhao?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/shivam.gupta.100?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/iaditya1441?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/jasnoor_jumber/?utm_source=qr',
    'https://www.instagram.com/nileshk2113/',
    'https://www.instagram.com/mdathar44__/',
    'https://www.instagram.com/niharika_singh_3620/'
  ],
  [
    '',
    'https://www.instagram.com/archit_soni3/',
    'https://instagram.com/pratishtha_dhiraj_?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/krishnapriya_213?r=nametag',
    'https://instagram.com/starun_siddharth?igshid=NTdlMDg3MTY=',
    'https://instagram.com/sksh.06?igshid=ZDdkNTZiNTM=',
    'http://instagram.com/anusha_mahajan4',
    'https://www.instagram.com/riteshlakra270419/',
    'https://instagram.com/dharmeshmahajan_',
    'https://www.instagram.com/gigamiles/',
    'https://instagram.com/theavanijangid?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/saketkr02?igshid=ZDdkNTZiNTM='
  ],
  [
    'https://www.instagram.com/nishu_07.02/',
    'https://instagram.com/pushpamberlia?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/singh_harsh1608/',
    'https://www.instagram.com/deependrasingh1037/',
    'https://instagram.com/abhishek_47146?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/deepaksai.majjiga?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/sachin_07_jnv/',
    'https://instagram.com/umanggarg41?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/tarun9be6?igshid=YmMyMTA2M2Y=',
    'https://www.instagram.com/divyansh_jain_777/',
    'https://instagram.com/abvbhi?igshid=YmMyMTA2M2Y=',
    'https://www.instagram.com/its_rishavrajput/',
    'https://www.instagram.com/harshitha_konam/',
    'https://instagram.com/_suraj_1902?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/ajaynayakkool?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/ipilbesra?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/vedxnsh___/',
    'http://instagram.com/dhruv30sharma13/',
    '',
    'https://instagram.com/ayushharshit999?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/gargi.nigam2107/',
    'https://www.instagram.com/simar.xxi/',
    'https://www.instagram.com/invites/contact/?i=tig3qdvl3mtl&utm_content=msl8hmi',
    'https://www.instagram.com/awasthiashutosh16/'
  ],
  [
    'https://instagram.com/ayushigupta400?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/ank.it7410?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/shreyanssshhh?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/ig_kshubham/',
    'https://www.instagram.com/01_mohit_02/',
    'https://www.instagram.com/_riyachauhan_09/',
    'https://instagram.com/1310amit21?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/_harsh.1510_/',
    'https://www.instagram.com/',
    'https://instagram.com/shivamraj0812?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/sainiharsh2908?igshid=MDE2OWE1N2Q=',
    'https://instagram.com/shivom6516?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/vaatsalya_sinha/',
    'https://www.instagram.com/apu.7.7/?next=%2F'
  ],
  [
    'http://www.instagram.com/avinash.singh___',
    'https://instagram.com/i.am.high_?igshid=ZDdkNTZiNTM=',
    'instagram.com/messy.medulla',
    'https://instagram.com/divyanshudevashish007?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/ravi_kumar.5/',
    'https://instagram.com/__.jaya.__1?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/inikhil.shukla?igshid=ZDdkNTZiNTM=',
    'instagram.com/vaibhav_gupta00/',
    'https://instagram.com/harshitanand543?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/anshukumar613?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/utkarshkumar83958?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/chande6526?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/aadix__12?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/kp_obviouslyop/',
    'https://instagram.com/sinha_aryan15?igshid=ZDdkNTZiNTM=',
    'http://instagram.com/rakshit_sawhney',
    'https://instagram.com/ayushsingh19002277?igshid=ZDdkNTZiNTM='
  ],
  [
    'https://instagram.com/sanskartotla?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/shubhamgrg123/',
    'https://instagram.com/sherlock_047?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/im_.vivek._?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/dhruxy_09?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/srinirohan3110?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/oye_tripathiiii___/',
    'https://instagram.com/v_ugosain?igshid=MWI4MTIyMDE=',
    'https://instagram.com/sandeepan_ghosh_0312?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/ayush.ag.05/',
    'https://www.instagram.com/krishnapriya_213?r=nametag',
    'https://instagram.com/mohale.ajinkya?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/sachinshaw09/',
    'http://instagram.com/naveen.0110',
    'https://instagram.com/udit_agarwal86?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/saumya5933?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/_vikrant__?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/gagan_mundada/?hl=en',
    'https://instagram.com/whysomundane?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/srbmaury/',
    'https://www.instagram.com/chaithanya.krishna3998/',
    'https://instagram.com/sravya_damarla?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/kanchu430?utm_medium=copy_link',
    'https://instagram.com/gopal_k_yadav?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/_aritra_datta__?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/d_dhathrichandra/',
    'https://www.instagram.com/akshatgupta_400/',
    'https://instagram.com/anvesh0183?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/agrawalmohit393?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/puravharan/',
    'https://instagram.com/prabhat.kumar10?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/dawdler_?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/jayesh._upadhyay?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/sandeep._.333?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/mausamsingh992001?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/sanidhya_v?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/h._rsha_133?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/shreyanssshhh?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/07.pawan.kumar?igshid=MWI4MTIyMDE=',
    'https://www.instagram.com/nishu_07.02/',
    'https://instagram.com/pushpamberlia?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/archit_soni3/',
    'https://www.instagram.com/mehulsahoo/',
    'https://www.instagram.com/a.nku.r/',
    'https://instagram.com/sainehaallu?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/vidhanpalresha?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/v_i_n_it_?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/piyush__12802?igshid=YmMyMTA2M2Y=',
    'https://www.instagram.com/devpal_6397/',
    'https://www.instagram.com/yogyatasingh1709/',
    'https://instagram.com/sumasri_palti?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/dhruw_bhupendra_03?igshid=YmMyMTA2M2Y=',
    'https://www.instagram.com/tusharkarale10/',
    'https://instagram.com/jnvkuldeep99?igshid=YmMyMTA2M2Y=',
    'https://www.instagram.com/aman_ag22/',
    'https://instagram.com/__om.1703__?igshid=YWJhMjlhZTc='
  ]
];
const ContactLinkedIn = [
  [
    '',
    'https://www.linkedin.com/in/pranav-mittal-4b15a0195',
    'https://www.linkedin.com/in/bisesh-agarwal-9779a01b7',
    'https://www.linkedin.com/in/atharva-bhatt-199665156',
    'https://www.linkedin.com/in/mayank-singh-1a5791204',
    'https://www.linkedin.com/in/sarang-manerikar/',
    'https://www.linkedin.com/in/shivansh-dubey-032916213/',
    'https://www.linkedin.com/in/suhani-agrawal-4030861bb/',
    'https://www.linkedin.com/in/ag-raghav26/',
    'https://www.linkedin.com/in/suryansh-singh-5b89461bb',
    'https://www.linkedin.com/in/akshit-singla-91b0aa220/',
    '',
    'https://www.linkedin.com/in/ankuragrawaldev',
    'https://www.linkedin.com/in/raina-jain-6b4b68143/',
    'https://www.linkedin.com/in/nishanth-gounder-15477a224/',
    'https://www.linkedin.com/in/avinash-singh-a03b86224',
    'https://www.linkedin.com/in/ayushi-gupta-125082212',
    'https://www.linkedin.com/in/ankit-kumar-252ab7222'
  ],
  [
    'https://www.linkedin.com/in/yash-jain-780332208',
    'https://www.linkedin.com/in/vikash-prajapati-a82ba01b0',
    'https://www.linkedin.com/in/vikhyath-venkatraman',
    'https://www.linkedin.com/in/anandsidd',
    'https://www.linkedin.com/in/eshaan-gupta-6b5b081b2',
    'https://www.linkedin.com/in/smriti06',
    'https://www.linkedin.com/in/prajakta-priyadarsini-3a83751ba',
    'https://www.linkedin.com/in/nisitha-vallamdasu-1170671a0',
    'https://www.linkedin.com/in/prince-kumar-gond-3b22b81b2',
    'https://www.linkedin.com/in/aditya-agarwal-662488204',
    'https://www.linkedin.com/in/swastik-thapa-526ba118a'
  ],
  [
    'https://www.linkedin.com/in/ankuragrawaldev',
    'https://www.linkedin.com/in/raina-jain-6b4b68143/',
    'https://www.linkedin.com/in/akash-kumar-371439246',
    'https://www.linkedin.com/in/avnesh-kumar-08b549230',
    'https://www.linkedin.com/in/kumar-sonu-453a23229',
    'https://www.linkedin.com/in/dhruv-chaudhary-4b6179233',
    'https://www.linkedin.com/in/anant-jain-8255a022b/',
    'https://www.linkedin.com/in/md-athar4403/',
    'https://www.linkedin.com/in/shubham-jaiswal-ece/',
    'https://www.linkedin.com/in/ashis7515/',
    'https://www.linkedin.com/in/nikhil-agarwal-2a3a8222b/',
    'https://www.linkedin.com/in/archit-pattanaik-486793230/',
    'https://www.linkedin.com/in/harshit-swarnkar-4a1890216/',
    'https://www.linkedin.com/in/nikhil-aggarwal-92819b235/',
    'https://www.linkedin.com/in/samarth-tankasali-16a20a235',
    'https://www.linkedin.com/in/samar-singh-randhawa-824377230/',
    'https://www.linkedin.com/in/mamalesh-hake-141872228'
  ],
  [
    'https://www.linkedin.com/in/devi-tanuja-vasamsetty-34b811218',
    'https://www.linkedin.com/in/vedharshini-korivi-060317224',
    'https://www.linkedin.com/in/riya-saini-ba7928229',
    'https://www.linkedin.com/in/kalpit-adhao-6a4a25206',
    'https://www.linkedin.com/in/shivam-gupta-4770a4230',
    'https://www.linkedin.com/in/aditya-mishra-8064481b8',
    'https://www.linkedin.com/in/jasnoor-sandhu-a6184021a/?originalSubdomain=in',
    'https://www.linkedin.com/in/sangle-nilesh-ganesh-4-year-b-tech-electronics-engineering-900377230/',
    'http://www.linkedin.com/in/md-athar4403',
    'https://www.linkedin.com/in/niharika-singh-947330243/'
  ],
  [
    'https://www.linkedin.com/in/shubhi-singh-b13aba220',
    'https://www.linkedin.com/in/archit-soni/',
    'https://www.linkedin.com/in/pratishtha-dhiraj-113754215',
    'https://www.linkedin.com/in/krishna-priya-p-1966b8224',
    'https://www.linkedin.com/in/tarun-siddharth-46a126235',
    'https://www.linkedin.com/in/sakshi-tomar-376581230',
    'https://www.linkedin.com/in/anusha-mahajan-136771194',
    'https://www.linkedin.com/in/ritesh-lakra-8128b7242?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BzAPoo0mUQryReB%2FNZkis4Q%3D%3D',
    'https://www.linkedin.com/in/dharmesh-mahajan-23574a223',
    'https://www.linkedin.com/in/shrirang-gupta-887383263/',
    'https://www.linkedin.com/in/avani-jangid-307564229',
    'https://www.linkedin.com/in/saket-kumar-singh-b35b39222'
  ],
  [
    'https://www.linkedin.com/in/nishanth-gounder-15477a224/',
    'https://www.linkedin.com/in/pushpam-berlia-89867b224',
    'https://www.linkedin.com/in/harsh-singh-952a42217/',
    'https://www.linkedin.com/in/deependra-singh-41943715a',
    'https://www.linkedin.com/in/abhishek-kumar-433300237',
    'https://www.linkedin.com/in/majjiga-deepak-sai-12b450230',
    'https://www.linkedin.com/in/sachin-kumar-9b128325a',
    'https://www.linkedin.com/in/umang-garg-8b30aa230',
    'https://www.linkedin.com/in/tarun-kumar-painkra-965535243',
    'https://www.linkedin.com/in/divyansh-jain-790468230/',
    'https://www.linkedin.com/in/abhishek-kumar-976578230',
    'https://www.linkedin.com/mwlite/in/rishav-kumar-a48a721b1',
    'https://www.linkedin.com/in/harshitha-konam-496118239/',
    'https://www.linkedin.com/in/suraj-gaur-22352a223',
    'http://linkedin.com/in/j-ajay-nayak-3a19a8230',
    'https://www.linkedin.com/in/ipil-besra-a42285230',
    'https://www.linkedin.com/in/vedansh-arya-1aa582230/',
    'http://www.linkedin.com/in/dhruv-sharma-84ba5b241',
    'http://www.linkedin.com/in/mitra-pidaparti-51191b256',
    'https://www.linkedin.com/in/ayush-harshit-4-year-b-tech-electronics-engineering-562460230',
    'https://www.linkedin.com/in/gargi-nigam-556569223/',
    'http://linkedin.com/in/simarpreet-singh-623312230',
    'https://www.linkedin.com/in/mauli-gupta-b44825227',
    'https://www.linkedin.com/in/ashutosh-awasthi-520240226/'
  ],
  [
    'https://www.linkedin.com/in/ayushi-gupta-125082212',
    'https://www.linkedin.com/in/ankit-kumar-252ab7222',
    'https://www.linkedin.com/in/shreyansh-jain-964357227',
    'https://www.linkedin.com/in/kshubham01/',
    'https://www.linkedin.com/in/mohit-singh-8a4628208/',
    'https://www.linkedin.com/in/riya-chauhan-867592230/',
    'https://www.linkedin.com/in/amit-kumar-4-year-b-tech-electronics-engineering-a02508230',
    'https://www.linkedin.com/mwlite/in/harsh-kumar-ba799925b',
    'https://www.linkedin.com/in/anshu-soni-3975a0229',
    'https://www.linkedin.com/in/shivam-raj-892233243',
    'https://www.linkedin.com/in/harsh-saini-092353230/',
    'https://www.linkedin.com/in/shivom-387607224',
    'https://www.linkedin.com/in/ vaatsalya-sinha-4-year-b-tech-electronics-engineering-887752263',
    'https://www.linkedin.com/in/rajat-shukla-9a0534230'
  ],
  [
    'https://www.linkedin.com/in/avinash-singh-a03b86224',
    'https://www.linkedin.com/in/bhavna-chavan',
    'https://www.linkedin.com/mwlite/in/paloxzz',
    'https://www.linkedin.com/in/divyanshu-devashish-186579230',
    'https://www.linkedin.com/in/ravi-kumar-meena-868150245/',
    'https://www.linkedin.com/in/jaya-kedia-4b6805235',
    'https://www.linkedin.com/in/anupam-shukla-888315257',
    'https://www.linkedin.com/in/vaibhav-gupta-53b0bb227',
    'https://www.linkedin.com/in/harshit-anand-5856b4239',
    'https://www.linkedin.com/in/anshu-k-0425b5227',
    'https://www.linkedin.com/in/utkarsh-kumar-4-year-b-tech-electronics-engineering-6b2564230',
    'https://www.linkedin.com/in/aditya-chandel-4-year-b-tech-electronics-engineering-874a3425b',
    'https://www.linkedin.com/in/aditya-kumar-a445a0223',
    'https://www.linkedin.com/in/khelan-mendapara-11736b223',
    'https://www.linkedin.com/in/aryan-sinha-24964022b?fbclid=PAAaYEWPAvdmJcz-A388x9mgSx65S5PVr7DhvkIkuikYL_sb-u7j2DRwoUfjA',
    'https://www.linkedin.com/in/rakshitsawhney',
    'https://www.linkedin.com/in/ayush-singh-b80573200'
  ],
  [
    'https://www.linkedin.com/in/sanskar-santosh-totla-427314200/',
    'https://www.linkedin.com/in/shubhamgrg1000/',
    'https://www.linkedin.com/in/aryan-909756207',
    'https://www.linkedin.com/in/vivek-agarwal-619004200',
    'https://www.linkedin.com/in/dhruxy',
    'https://www.linkedin.com/mwlite/in/srini-rohan-gujulla-leel-9ab533219',
    'https://www.linkedin.com/in/vaibhav-tripathi-270b46204',
    'https://www.linkedin.com/in/vishal-gosain-a5719420b',
    'https://www.linkedin.com/in/sandeepan-ghosh-a67774222',
    'https://www.linkedin.com/in/ayush-agarwal-261041215/',
    'https://www.linkedin.com/in/krishna-priya-p-1966b8224',
    'https://www.linkedin.com/in/ajinkya-mohale-81b146204',
    'https://www.linkedin.com/in/sachin-shaw-790015228/',
    'http://linkedin.com/in/nk-yadav',
    'https://www.linkedin.com/in/udit-agarwal86',
    'https://www.linkedin.com/in/saumya-chaudhary-ab0097224?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bc810zZBRQtKwylcOzfAQtg%3D%3D',
    'https://www.linkedin.com/in/vikrant-kumar-73bab2206',
    'https://www.linkedin.com/in/gagan-mundada-19ba09229/',
    'https://www.linkedin.com/in/bhargavi-kiran-a53326224',
    'https://www.linkedin.com/in/saurabh-maurya-39b04b205/',
    'https://www.linkedin.com/in/chaithanya-krishna-231a021b6/',
    'https://www.linkedin.com/in/sravya-damarla-631931206',
    'https://www.linkedin.com/in/kanchan-khadda-450068204',
    'https://www.linkedin.com/in/gopal-krishna-yadav-7ba77022b',
    'https://www.linkedin.com/in/aritra-datta/',
    'http://www.linkedin.com/in/dasari-dhathri-chandra-0a1407230',
    'https://www.linkedin.com/in/akshat-gupta-9b7689253/',
    'https://www.linkedin.com/in/anvesh-gupta-894647228',
    'https://www.linkedin.com/in/mohit-kumar-agrawal-79b544230',
    'https://www.linkedin.com/in/purav-haran-62004222b',
    'http://www.linkedin.com/in/prabhat-kumar-iitbhu',
    'https://www.linkedin.com/in/rohit-gautam-271a211b8',
    'https://www.linkedin.com/in/jayesh-upadhyay-84b46b210',
    'https://www.linkedin.com/in/sandeep-bollepally-234283217',
    'https://www.linkedin.com/in/mausam-singh-4-year-b-tech-electronics-engineering-46492022a',
    'https://www.linkedin.com/in/sanidhya-verma-2099b71b1',
    'https://www.linkedin.com/in/harsha-sree-sanapala-26b0bb218',
    'https://www.linkedin.com/in/shreyansh-jain-964357227',
    'https://www.linkedin.com/mwlite/in/pawan-kumar-147073223',
    'https://www.linkedin.com/in/nishanth-gounder-15477a224/',
    'https://www.linkedin.com/in/pushpam-berlia-89867b224',
    'https://www.linkedin.com/in/archit-soni/',
    'https://www.linkedin.com/in/mehul-kumar-sahoo-a3b5a0230/',
    'https://www.linkedin.com/mwlite/in/ankur-shandilya-064577230',
    'https://www.linkedin.com/in/saineha-allu-111797223',
    'https://www.linkedin.com/in/vidhan-palresha-53568a223',
    'https://www.linkedin.com/in/vinit-sharma-703b00253/',
    'https://www.linkedin.com/in/piyush-lodwal-02228b223/',
    'https://www.linkedin.com/in/devpal-dan-265578230/',
    'https://www.linkedin.com/in/yogyata-singh-278096230/',
    'https://www.linkedin.com/in/sumasri-palti-6ba965230',
    'https://www.linkedin.com/in/bhupendra-kumar-dhruw-897423230',
    'https://www.linkedin.com/in/tushar-karale-88957b230/',
    'https://www.linkedin.com/in/kuldeep-singh-b58381255',
    'https://www.linkedin.com/in/aman-agrawal-20632b230',
    'https://www.linkedin.com/in/om-verma-a16547229'
  ]
];
export { TeamMemberName, TeamDomain, Designation, TeamMemberDetails, ContactMail, ContactInstagram, ContactLinkedIn, MemberImage };
